LesseeClient/Models/ErrorViewModel.cs
using System;

namespace LesseeClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LesseeClient/Models/Hardware.cs
using System;

namespace LesseeClient.Models
{
    public class Hardware
    {
        public string Name { get; set; }
        public string IP { get; set; }
        public bool Leased { get; set; }
        public Platform Platform { get; set; }
    }
}

LesseeClient/Models/Lease.cs
using System;

namespace LesseeClient.Models
{
    public class Lease
    {
        public Hardware Hardware { get; set; }
        public DateTime Start { get; set; }
        public DateTime End { get; set; }
        public Boolean Active { get; set; }
    }
}

LesseeClient/Models/Platform.cs
using System;

namespace LesseeClient.Models
{
    public class Platform
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }
}

LesseeClient/Controllers/HardwaresController.cs
using Microsoft.AspNetCore.Mvc;
using LesseeClient.Caller.Callers;


namespace LesseeClient.Controllers
{
    public class HardwaresController : Controller
    {
        // GET: /Hardwares/
        public IActionResult Index(string message, string platform)
        {
            var caller = new RestSharpCaller(Constants.baseUrl);
            var platforms = caller.GetPlatforms();
            var hardwares = caller.GetHardwares(platform);
            ViewBag.hardwares = hardwares;
            ViewBag.platforms = platforms;
            ViewBag.message = message;   

            return View();
        }

        // GET: /Hardwares/Add/
        public IActionResult Add()
        {
            var caller = new RestSharpCaller(Constants.baseUrl);
            var platforms = caller.GetPlatforms();
            return View(platforms);
        }
    }
}

LesseeClient/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using LesseeClient.Models;
using LesseeClient.Caller.Callers;

namespace LesseeClient.Controllers
{
    public class HomeController : Controller
    {
        // GET: /Home/
        public IActionResult Index(string message, string errorMsg)
        {
            var caller = new RestSharpCaller(Constants.baseUrl);
            var platforms = caller.GetPlatforms();
            ViewBag.platforms = platforms;
            ViewBag.message = message;
            ViewBag.errorMsg = errorMsg;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LesseeClient/Controllers/LeasesController.cs
using LesseeClient.Caller.Callers;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LesseeClient.Controllers
{
    public class LeasesController : Controller
    {
        // GET: /Leases/
        public IActionResult Index(string active)
        {
            var caller = new RestSharpCaller(Constants.baseUrl);
            var leases = caller.GetLeases(active);
            ViewBag.leases = leases;

            return View();
        }
    }
}

LesseeClient/Views/Hardwares/Add.cshtml
@{
    ViewData["Title"] = "Add Hardware";
}

<br />
<div class="row">
    <div class="col-sm-12 col-md-6 col-md-offset-3">
        <h2>Add hardware:</h2>
        <form>
            <div class="form-group">
                <label for="platform">Select platform:</label>
                <select class="form-control" id="platform">
                    @foreach (var platform in Model)
                    {
                    <option value="@platform.Id">@platform.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" placeholder="Enter name">
            </div>
            <div class="form-group">
                <label for="ip">IP</label>
                <input type="text" class="form-control" id="ip" placeholder="Enter IP address">
            </div>
            <center>
                <input type="button" value="Add Hardware" class="btn btn-primary center" onclick="AddHardware()"/>
            </center>
        </form>
    </div>
</div>

LesseeClient/Views/Hardwares/Index.cshtml
@{
    ViewData["Title"] = "Hardwares";
}

<br />
<div class="row">
    <div class="col-sm-12">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-success dropdown-toggle" 
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select Platform
            </button>
            <div class="dropdown-menu">
                @foreach (var platform in @ViewBag.platforms) { 
                     <a class="dropdown-item" href="/Hardwares/Index/?platform=@platform.Id">@platform.Name</a>
                }
            </div>
        </div>
        <button class="btn btn-primary pull-right block-button" onClick='redirectOnClick()'>Add Hardware</button>
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Hardware</th>
                    <th>IP</th>
                    <th>Status</th>
                    <th>Platform</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var hardware in @ViewBag.hardwares)
                {
                    <tr>
                        <td>@hardware.Name</td>
                        <td>@hardware.IP</td>
                        @if (@hardware.Leased)
                        {
                            <td><span class="badge badge-danger">Leased</span></td>
                            /**/

                        }
                        else
                        {
                            <td><span class="badge badge-success">Available</span></td>
                        }
                        <td>@hardware.Platform.Name</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>function redirectOnClick() {
        document.location = '/Hardwares/Add';
}</script>

LesseeClient/Views/Hardwares/Post.cshtml
@{
    ViewData["Title"] = "Hardwares";
}

<br />
<div class="row">
    <div class="col-sm-12">
        <p>Hardware was added succesfully</p>
    </div>
</div>

LesseeClient/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

LesseeClient/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LesseeClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="platformCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#platformCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#platformCarousel" data-slide-to="1"></li>
        <li data-target="#platformCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        @{ int index = 0;}
        @if (@ViewBag.platforms != null) { 
            @foreach (var platform in @ViewBag.platforms) {
                var extraClass = "";
                if (index == 0) {
                    extraClass = "active";
                }
            <div class="item @extraClass">
                @if (platform.Name == "XboxOne") {
                    <img src="~/images/xboxone.jpeg" alt="Xbox One" class="img-responsive" />
                } else if (platform.Name == "PS4") {
                    <img src="~/images/ps4.jpeg" alt="PS4" class="img-responsive" />
                } else if (platform.Name == "PC") {
                    <img src="~/images/pc.jpg" alt="PC" class="img-responsive" />
                } else { 
                    <img src="~/images/default.jpg" alt="PC" class="img-responsive" />
                }

                <div class="carousel-caption" role="option">
                    <p>
                        <a class="btn btn-default" href="/Hardwares/Index/?platform=@platform.Id">
                            See More @platform.Name hardware
                        </a>
                    </p>
                </div>

            </div>
                index++;
            }
        }

    </div>
    <a class="left carousel-control" href="#platformCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#platformCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<br />
<div class="row">

    <div class="col-sm-12 col-md-6 col-md-offset-3">
        <h2>Lease a hardware:</h2>
        <form>
            <div class="form-group">
                <label for="platform">Select platform:</label>
                <select class="form-control" id="platform">
                    @foreach (var platform in @ViewBag.platforms)
                    {
                        <option value="@platform.Id">@platform.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label for="duration">Duration</label>
                <input type="text" class="form-control" id="duration" placeholder="Minutes">
            </div>
            <center>
                <input type="button" value="Lease Hardware" class="btn btn-primary center" onclick="LeaseHardware()" />
            </center>
        </form>
    </div>
</div>

LesseeClient/Views/Leases/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@{
    ViewData["Title"] = "Hardwares";
}

<br />
<div class="row">
    <div class="col-sm-12">
        <button class="btn btn-primary pull-right block-button" onClick='window.location="/Leases/Index?active=true"'>
        Show Active
        </button>
        <button class="btn btn-primary pull-right block-button" onClick='window.location="/Leases/Index"'>
        Show All
        </button>
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Hardware</th>
                    <th>IP</th>
                    <th>Platform</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var lease in @ViewBag.leases)
                {
                <tr>
                    <td>@lease.Hardware.Name</td>
                    <td>@lease.Hardware.IP</td>
                    <td>@lease.Hardware.Platform.Name</td>
                    @if (@lease.Active)
                    {
                    <td><span class="badge badge-danger">Active</span></td>
                    /**/

                    }
                    else
                    {
                    <td><span class="badge badge-success">Not active</span></td>
                    }
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
function redirectOnClick() {
        document.location = '/Leases/Index?active=true';
}</script>

LesseeClient/Views/Platforms/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Platforms";
}

<div class="row">
    <div class="col-sm-12">
        <button type="button" class="btn">XboxOne</button>
        <button type="button" class="btn">PC</button>
        <button type="button" class="btn">PS4</button>
    </div>
</div>

LesseeClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Lessee</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LesseeClient</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Hardwares" asp-action="Index">Hardwares</a></li>
                        <li><a asp-area="" asp-controller="Leases" asp-action="Index">Leases</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            <br />
            @if(@ViewBag.message != null)
            {
            <div class="alert alert-success" role="alert">
                @ViewBag.message
            </div>
            }
            
            @if(@ViewBag.errorMsg != null)
            {
            <div class="alert alert-danger" role="alert">
                @ViewBag.errorMsg
            </div>
            }
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - Lessee</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </body>
</html>